### ISSUE TITLE
Mobile images

### ISSUE THREAD

**Issue by bolach** [gta191977649/Random-image#1]
Hello
When we use script on mobile (visit website), some images are not 100% fit . Its possible to fix it?

**Comment by gta191977649** [comment]
@bolach can you give me an example? e.g how did you show the image?

**Comment by bolach** [comment]
@gta191977649 i sent to you by mail. I hope you dont mind :)

**Comment by gta191977649** [comment]
@bolach  please try to use the <img> tag as possible, e.g. if this script is in http://localhost/random-imgage/ then you can try something like this `<img src="http://localhost/random-imgage/index.php" width=100% height=100%> `

**Comment by bolach** [comment]
But i want to use on my domain
Everytime i use www.mydomain.com , it shows a different image, but with 100% fit to screen. How can i adapt that?

**Comment by gta191977649** [comment]
@bolach try something like this,
let's say if you put this script inside the Random-image folder in your web folder, then outside Random-image folder (which is your web root) you can create an index.html and add following code into it
`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="ie=edge"><title>Document</title></head><body><img src="./Random-image" width="100%" height="100%"></body></html>`
when you access to your www.mydomain.com, it will accees to the index.html,which will show the image 100% fit screen

**Comment by bolach** [comment]
I understand now what you mean! Thank you!
